# Generated by Django 5.2.15 on 2026-06-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('morning', models.TextField()),
                ('afternoon', models.TextField()),
                ('evening', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'day_number'), name='unique_trip_day')],
            },
        ),
        migrations.CreateModel(
            name='ItineraryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('morning', models.TextField()),
                ('afternoon', models.TextField()),
                ('evening', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_templates', to='destinations.destination')),
            ],
            options={
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('destination', 'day_number'), name='unique_destination_day')],
            },
        ),
    ]
