# Generated by Django 5.2.15 on 2026-08-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_itineraryday_itinerarytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_covers/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(default='My Awesome Trip', max_length=200),
        ),
    ]
