# Generated by Django 5.2.15 on 2026-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_cover_image_trip_description_trip_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_name',
            field=models.CharField(blank=True, default='My Awesome Trip', max_length=200),
        ),
    ]
