# Generated by Django 5.2.15 on 2026-08-22 10:02 — fixed for existing rows

import uuid
from django.db import migrations, models


def populate_share_tokens(apps, schema_editor):
    """Assign a unique UUID token to every existing trip row."""
    Trip = apps.get_model('trips', 'Trip')
    for trip in Trip.objects.all():
        trip.share_token = uuid.uuid4()
        trip.save(update_fields=['share_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_trip_name'),
    ]

    operations = [
        # 1. Add is_public (no uniqueness issue)
        migrations.AddField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        # 2. Add share_token WITHOUT unique constraint first
        migrations.AddField(
            model_name='trip',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # 3. Backfill every existing row with its own unique UUID
        migrations.RunPython(populate_share_tokens, migrations.RunPython.noop),
        # 4. Now apply the unique constraint safely
        migrations.AlterField(
            model_name='trip',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
