# Generated by Django 5.2.15 on 2026-06-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('average_visit_time', models.PositiveIntegerField(default=60, help_text='Average visit time in minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination')),
            ],
        ),
    ]
