# Generated by Django 5.2.15 on 2026-06-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('peak_months', models.CharField(max_length=200)),
                ('average_temperature', models.CharField(max_length=100)),
                ('rainfall', models.CharField(max_length=100)),
                ('travel_tip', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_seasons', to='destinations.destination')),
            ],
        ),
    ]
