# Generated by Django 5.2.15 on 2026-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('best_season', models.CharField(max_length=100)),
                ('ideal_days', models.PositiveIntegerField(default=1)),
                ('budget_level', models.CharField(choices=[('Budget', 'Budget'), ('Moderate', 'Moderate'), ('Luxury', 'Luxury')], max_length=20)),
                ('average_cost_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_friendly', models.BooleanField(default=True)),
                ('couple_friendly', models.BooleanField(default=True)),
                ('solo_friendly', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
            ],
        ),
    ]
