# Generated by Django 5.2.15 on 2026-07-02 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=50)),
                ('travel_type', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('num_travellers', models.PositiveIntegerField()),
                ('state', models.CharField(blank=True, max_length=100)),
                ('results', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
